services:
  yamlcv:
    build: .
    ports:
      - "7878:7878"
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./generated:/app/generated
      - ./templates:/app/templates
    command:
      [
        "uv",
        "run",
        "server.py",
        "--details",
        "/app/templates/jake/details.personal.yml",
      ]
